# Global configuration shared across all charts
#global:
  # Deployment environment
  #env:

  # Application
  #app:

# Default value for host key.
# Can be overridden by the host key.
# If not host key provided:
#
#     - If global.env == "prod": host set to defaultHost
#     - Else: host set to {{ .Values.global.env }}-{{ .Values.defaultHost }}
#
# (Required)
#defaultHost:

# Internal port HTTP service will listen on
# (Required)
#port:

# Values for a ConfigMap resource
# Saved under key with value in a ConfigMap
# If envKey exists value passed to app container via environment
# variable envKey.
#configMap:
  #- key:
  #  value:
  #  envKey:

# If present will mount ConfigMap under path in app container
#configMapMount:

# Values for a Secret resource
# Saved under the key with value in a Secret
# If envKey exists value passed to app container via environment
# variable envKey.
#secret:
  #- key:
  #  value:
  #  envKey:

# If present will mount Secret under path in app container
#secretMount:

# MongoDB configuration
#mongo:
  # If true will provide MongoDB information from github.com/kscout/mongo-chart
  # to the app pod via environment variables
  #enabled:

  # Environment variable to set to db password
  # Defaults to APP_DB_PASSWORD
  #dbPasswordEnvKey:

  # Environment variable to set to db name
  # Defaults to APP_DB_NAME
  #dbNameEnvKey:

  # Environment variable set to db host
  # Defaults to APP_DB_HOST
  #dbHostEnvKey:

# Environment variables passed to app pod
#env:
  # - name:
  #   value:

# volumes made available to pod
#volumes:
  # Each object is passed directly to the deploymentconfig.spec.volumes field
  #- name:
  #...

# Volume mounts passed to app pod
#volumeMounts:
  #- name:
  #  mountPath:
  #  readOnly:
