{{ if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}-config
  labels:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
data:
  {{- range .Values.configMap }}
  {{ .key }}: {{ tpl .value $ }}
  {{- end }}
{{ end }}
