apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}-gh-webhook-secret
  labels:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
type: Opaque
data:
  WebHookSecretKey: {{ .Values.ghWebhookSecret | b64enc }}
