apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}
  labels:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
spec:
  host: {{ template "http-service.host" . }}
  path: /
  to:
    kind: Service
    name: {{ .Values.global.env }}-{{ .Values.global.app }}
    weight: 100
  port:
    targetPort: proxy-http
  tls:
    termination: edge
status:
  ingress:
    - host: {{ template "http-service.host" . }}
