apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}
  labels:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: proxy-http
      name: proxy-http
