apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}
  labels:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
spec:
  dockerImageRepository: docker.io/kscout/{{ .Values.global.app }}
  tags:
    - from:
        kind: DockerImage
        name: docker.io/kscout/{{ .Values.global.app }}:{{ .Values.global.env }}-latest
      name: {{ .Values.global.env }}-latest
      importPolicy:
        scheduled: true
