apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}
  labels:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
spec: {}
