apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.env }}-serverless-registry-api-metrics
  labels:
    app: serverless-registry-api
    component: api
    env: {{ .Values.global.env }}
spec:
  type: ClusterIP
  selector:
    app: serverless-registry-api
    component: api
    env: {{ .Values.global.env }}
  ports:
    - protocol: TCP
      port: 9180
      targetPort: proxy-metrics
      name: proxy-metrics
