{{- if .Values.metricsEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}-metrics
  labels:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
  ports:
    - protocol: TCP
      port: {{ .Values.metricsPort }}
      targetPort: metrics
      name: metrics
{{- end }}
