{{ if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}-secret
  labels:
    app: {{ .Values.global.app }}
    component: app
    env: {{ .Values.global.env }}
type: Opaque
data:
  {{- range .Values.secret }}
  {{ .key }}: {{ .value | b64enc }}
  {{- end }}
{{ end }}
